#include "frontend.cpp"
#include "login/login.cpp"
#include "logout/logout.cpp"
#include "utility/utility.cpp"
#include "appState/appState.cpp"
#include "listusers/listusers.cpp"
#include "listbids/listbids.cpp"
#include "bid/bid.cpp"